#ifndef BMS_TYPEDEFS_H_
#define BMS_TYPEDEFS_H_

typedef enum {
    BMS_OK = 0,
    BMS_ERROR_COMM_TIMEOUT,
    BMS_ERROR_CRC,
    BMS_ERROR_INVALID_RESPONSE,
    BMS_ERROR_WAKEUP_FAILED,
    BMS_ERROR_AUTOADDRESS_FAILED,
    BMS_ERROR_CONFIG_FAILED,
    BMS_ERROR_FAULT_ACTIVE,
    BMS_ERROR_UNKNOWN
} BMSErrorCode_t;

#endif